(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=ba(this);function r(a,b){if(b)a:{var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,g){this.g=h;p(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=q[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function t(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},u;if("function"==typeof Object.setPrototypeOf)u=Object.setPrototypeOf;else{var v;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;v=ia.a;break a}catch(a){}v=!1}u=v?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=u;
function ka(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.A=0;this.j=null}function la(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}ka.prototype.s=function(a){this.i=a};function ma(a,b){a.j={aa:b,ba:!0};a.g=a.A}ka.prototype.return=function(a){this.j={return:a};this.g=this.A};function w(a,b,c){a.g=c;return{value:b}}function na(a){this.g=new ka;this.h=a}
function oa(a,b){la(a.g);var c=a.g.h;if(c)return pa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return x(a)}function pa(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.l=!1,e;var h=e.value}catch(g){return a.g.h=null,ma(a.g,g),x(a)}a.g.h=null;d.call(a.g,h);return x(a)}
function x(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,ma(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.ba)throw b.aa;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function qa(a){this.next=function(b){la(a.g);a.g.h?b=pa(a,a.g.h.next,b,a.g.s):(a.g.s(b),b=x(a));return b};this.throw=function(b){la(a.g);a.g.h?b=pa(a,a.g.h["throw"],b,a.g.s):(ma(a.g,b),b=x(a));return b};this.return=function(b){return oa(a,b)};this[Symbol.iterator]=function(){return this}}function ra(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(h,e)}h(a.next())})}
function y(a){return ra(new qa(new na(a)))}
r("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.A=!1;var f=this.j();try{g(f.resolve,f.reject)}catch(k){f.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(f){f(g)})}if(a)return a;c.prototype.h=function(g){if(null==this.g){this.g=[];var f=this;this.i(function(){f.l()})}this.g.push(g)};var e=q.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var f=0;f<g.length;++f){var k=
g[f];g[f]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(l){return function(m){k||(k=!0,l.call(f,m))}}var f=this,k=!1;return{resolve:g(this.W),reject:g(this.l)}};b.prototype.W=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.Y(g);else{a:switch(typeof g){case "object":var f=null!=g;break a;case "function":f=!0;break a;default:f=!1}f?this.V(g):this.s(g)}};
b.prototype.V=function(g){var f=void 0;try{f=g.then}catch(k){this.l(k);return}"function"==typeof f?this.Z(f,g):this.s(g)};b.prototype.l=function(g){this.U(2,g)};b.prototype.s=function(g){this.U(1,g)};b.prototype.U=function(g,f){if(0!=this.h)throw Error("Cannot settle("+g+", "+f+"): Promise already settled in state"+this.h);this.h=g;this.i=f;2===this.h&&this.X();this.ca()};b.prototype.X=function(){var g=this;e(function(){if(g.da()){var f=q.console;"undefined"!==typeof f&&f.error(g.i)}},1)};b.prototype.da=
function(){if(this.A)return!1;var g=q.CustomEvent,f=q.Event,k=q.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof f?g=new f("unhandledrejection",{cancelable:!0}):(g=q.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.ca=function(){if(null!=this.g){for(var g=0;g<this.g.length;++g)h.h(this.g[g]);this.g=null}};var h=new c;b.prototype.Y=
function(g){var f=this.j();g.B(f.resolve,f.reject)};b.prototype.Z=function(g,f){var k=this.j();try{g.call(f,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,f){function k(B,E){return"function"==typeof B?function(ea){try{l(B(ea))}catch(fa){m(fa)}}:E}var l,m,z=new b(function(B,E){l=B;m=E});this.B(k(g,l),k(f,m));return z};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.B=function(g,f){function k(){switch(l.h){case 1:g(l.i);break;case 2:f(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;null==this.g?h.h(k):this.g.push(k);this.A=!0};b.resolve=d;b.reject=function(g){return new b(function(f,k){k(g)})};b.race=function(g){return new b(function(f,k){for(var l=t(g),m=l.next();!m.done;m=l.next())d(m.value).B(f,k)})};b.all=function(g){var f=t(g),k=f.next();return k.done?d([]):new b(function(l,m){function z(ea){return function(fa){B[ea]=fa;E--;0==E&&l(B)}}var B=[],E=0;do B.push(void 0),E++,d(k.value).B(z(B.length-1),m),k=f.next();while(!k.done)})};return b});
function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(k){this.g=(f+=Math.random()+1).toString();if(k){k=t(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!A(k,g)){var l=new c;p(k,g,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(z){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var f=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!A(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&A(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&A(k,
g)&&A(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&A(k,g)&&A(k[g],this.g)?delete k[g][this.g]:!1};return b});
r("Map",function(a){function b(){var f={};return f.u=f.next=f.head=f}function c(f,k){var l=f.g;return ca(function(){if(l){for(;l.head!=f.g;)l=l.u;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(f,k){var l=k&&typeof k;"object"==l||"function"==l?h.has(k)?l=h.get(k):(l=""+ ++g,h.set(k,l)):l="p_"+k;var m=f.h[l];if(m&&A(f.h,l))for(f=0;f<m.length;f++){var z=m[f];if(k!==k&&z.key!==z.key||k===z.key)return{id:l,list:m,index:f,o:z}}return{id:l,list:m,
index:-1,o:void 0}}function e(f){this.h={};this.g=b();this.size=0;if(f){f=t(f);for(var k;!(k=f.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),k=new a(t([[f,"s"]]));if("s"!=k.get(f)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=f||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!l.next().done?!1:!0}catch(z){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(f,k){f=0===f?0:f;var l=d(this,f);l.list||(l.list=this.h[l.id]=[]);l.o?l.o.value=k:(l.o={next:this.g,u:this.g.u,head:this.g,key:f,value:k},l.list.push(l.o),this.g.u.next=l.o,this.g.u=l.o,this.size++);return this};e.prototype.delete=function(f){f=d(this,f);return f.o&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.h[f.id],f.o.u.next=f.o.next,f.o.next.u=f.o.u,f.o.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.u=b();this.size=0};e.prototype.has=function(f){return!!d(this,f).o};e.prototype.get=function(f){return(f=d(this,f).o)&&f.value};e.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};e.prototype.keys=function(){return c(this,function(f){return f.key})};e.prototype.values=function(){return c(this,function(f){return f.value})};e.prototype.forEach=function(f,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,
f.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
r("Set",function(a){function b(c){this.g=new Map;if(c){c=t(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(t([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),h=e.next();if(h.done||h.value[0]!=c||h.value[1]!=c)return!1;h=e.next();return h.done||h.value[0]==c||4!=h.value[0].x||
h.value[1]!=h.value[0]?!1:e.next().done}catch(g){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(h){return c.call(d,h,h,e)})};return b});r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var g=d[h];if(b.call(c,g,h,d)){b=g;break a}}b=void 0}return b}});r("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});
r("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});function sa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return sa(this,function(b){return b})}});
r("Array.prototype.values",function(a){return a?a:function(){return sa(this,function(b,c){return c})}});r("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});r("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});
r("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});var C=this||self;function D(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function F(a,b){a=a.split(".");var c=C;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function ta(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ea=function(d,e,h){for(var g=Array(arguments.length-2),f=2;f<arguments.length;f++)g[f-2]=arguments[f];return b.prototype[e].apply(d,g)}};function G(a,b){a=Error.call(this,a);this.message=a.message;"stack"in a&&(this.stack=a.stack);b=void 0===b?2:b;this.code=1E4<b?Math.floor(b/1E4):b}var H=Error;G.prototype=da(H.prototype);G.prototype.constructor=G;if(ja)ja(G,H);else for(var I in H)if("prototype"!=I)if(Object.defineProperties){var ua=Object.getOwnPropertyDescriptor(H,I);ua&&Object.defineProperty(G,I,ua)}else G[I]=H[I];G.T=H.prototype;F("microapps.ErrorCode.CANCELLED",1);F("microapps.ErrorCode.UNKNOWN",2);F("microapps.ErrorCode.INVALID_ARGUMENT",3);F("microapps.ErrorCode.DEADLINE_EXCEEDED",4);F("microapps.ErrorCode.NOT_FOUND",5);F("microapps.ErrorCode.ALREADY_EXISTS",6);F("microapps.ErrorCode.PERMISSION_DENIED",7);F("microapps.ErrorCode.RESOURCE_EXHAUSTED",8);F("microapps.ErrorCode.FAILED_PRECONDITION",9);F("microapps.ErrorCode.ABORTED",10);F("microapps.ErrorCode.OUT_OF_RANGE",11);F("microapps.ErrorCode.UNIMPLEMENTED",12);
F("microapps.ErrorCode.INTERNAL",13);F("microapps.ErrorCode.UNAVAILABLE",14);F("microapps.ErrorCode.DATA_LOSS",15);F("microapps.ErrorCode.UNAUTHENTICATED",16);var J=null;function va(){}n=va.prototype;n.C=function(){J().C()};n.K=function(a){return J().K(a)};n.P=function(a){return J().P(a)};n.R=function(a){return J().R(a)};n.F=function(a){return J().F(a)};n.J=function(a){return J().J(a)};n.M=function(a){return J().M(a)};n.N=function(a){return J().N(a)};n.O=function(a){return J().O(a)};n.v=function(a){return J().v(a)};n.I=function(a){return J().I(a)};var wa=null;function xa(){}xa.prototype.L=function(){return wa().L()};xa.prototype.G=function(a){return wa().G(a)};var ya=new Set(["image/jpeg","video/*","application/pdf"]),za=new Set(["camera","files"]);function Aa(a,b){a=String(a).toLowerCase();b=String(b).toLowerCase();return a<b?-1:a==b?0:1};function K(){var a=C.navigator;return a&&(a=a.userAgent)?a:""}function L(a){return-1!=K().indexOf(a)};var Ba=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ca=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0};
function M(a){return Array.prototype.concat.apply([],arguments)};function Da(a){Da[" "](a);return a}Da[" "]=function(){};var Ea=L("Gecko")&&!(-1!=K().toLowerCase().indexOf("webkit")&&!L("Edge"))&&!(L("Trident")||L("MSIE"))&&!L("Edge"),Fa=L("Android"),Ga=L("iPhone")&&!L("iPod")&&!L("iPad")||L("iPad")||L("iPod");var Ha=/^(http:\/\/localhost\.corp|https:\/\/microapps(-(autopush|preprod|prod-tt|daily-[0-6])\.sandbox)?)\.google\.com(:[0-9]+)?$/;function Ia(a){var b=0,c;for(c in a)b++;return b}function Ja(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;for(var d in b)if(!(d in a))return!1;return!0};function N(a,b){this.g=b===Ka?a:""}N.prototype.toString=function(){return this.g.toString()};var Ka={},O=new N("about:blank",Ka);var La=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ma(a){return a?decodeURI(a):a};function Na(a){if(a.self===a.top)return!1;if(a.location.origin&&a.location.ancestorOrigins){var b=a.location.origin;return Ca(a.location.ancestorOrigins,function(c){var d=Ma(c.match(La)[3]||null)||"";return 0==Aa(".google.com",d.slice(d.length-11))||c===b})}return!1}function Oa(a){return a.location.ancestorOrigins&&a.location.ancestorOrigins.length?Ha.test(a.location.ancestorOrigins[0]):!1};var Pa=/\[gpay-microapps\/(\d+(\.\d+)*)[^\]]*\]/;function Qa(a,b,c){this.g=a;this.h=b;this.i=c}function Ra(a){a=a.split(".");return new Qa(Number(a[0]||""),Number(a[1]||""),Number(a[2]||""))}
function P(){var a={j:"",l:!1,h:!1,g:0};Fa?a.j="android":Ga&&(a.j="ios");var b=Pa.exec(K().toLocaleLowerCase());b&&0<b.length&&("android"==a.j&&b[0].includes("dev")?a.l=!0:"ios"==a.j&&b[0].includes("213.999.9999")?a.l=!0:b&&1<b.length&&(a.i=Ra(b[1])),b[0].includes("flutter")&&(a.h=!0),b[0].includes("merchant")?a.g=5:a.g=Sa(a));return a}function Sa(a){if(!a)return 0;switch(a.j){case "ios":return a.h?2:4;case "android":return a.h?1:3;default:return 0}};function Ta(){};function Ua(a,b){this.type=a;this.target=b}Ua.prototype.g=function(){};var Va=function(){if(!C.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{C.addEventListener("test",function(){},b),C.removeEventListener("test",function(){},b)}catch(c){}return a}();function Q(a){Ua.call(this,a?a.type:"");this.relatedTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.H=null;if(a){var b=this.type=a.type,c=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;var d=a.relatedTarget;if(d){if(Ea){a:{try{Da(d.nodeName);var e=!0;break a}catch(h){}e=!1}e||(d=
null)}}else"mouseover"==b?d=a.fromElement:"mouseout"==b&&(d=a.toElement);this.relatedTarget=d;c?(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY,this.screenX=c.screenX||0,this.screenY=c.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Wa[a.pointerType]||"";this.state=a.state;this.H=a;a.defaultPrevented&&Q.T.g.call(this)}}ta(Q,Ua);var Wa={2:"touch",3:"pen",4:"mouse"};Q.prototype.g=function(){Q.T.g.call(this);var a=this.H;a.preventDefault?a.preventDefault():a.returnValue=!1};var Xa="closure_listenable_"+(1E6*Math.random()|0);var Ya=0;function Za(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.h=e;this.key=++Ya;this.g=this.D=!1}function $a(a){a.g=!0;a.listener=null;a.proxy=null;a.src=null;a.h=null};function ab(a){this.src=a;this.g={};this.h=0}ab.prototype.add=function(a,b,c,d,e){var h=a.toString();a=this.g[h];a||(a=this.g[h]=[],this.h++);var g;a:{for(g=0;g<a.length;++g){var f=a[g];if(!f.g&&f.listener==b&&f.capture==!!d&&f.h==e)break a}g=-1}-1<g?(b=a[g],c||(b.D=!1)):(b=new Za(b,this.src,h,!!d,e),b.D=c,a.push(b));return b};var bb="closure_lm_"+(1E6*Math.random()|0),cb={},db=0;function eb(a,b,c,d,e){if(d&&d.once)return R(a,b,c,d,e);if(Array.isArray(b)){for(var h=0;h<b.length;h++)eb(a,b[h],c,d,e);return null}c=fb(c);return a&&a[Xa]?a.g(b,c,D(d)?!!d.capture:!!d,e):gb(a,b,c,!1,d,e)}
function gb(a,b,c,d,e,h){if(!b)throw Error("Invalid event type");var g=D(e)?!!e.capture:!!e,f=hb(a);f||(a[bb]=f=new ab(a));c=f.add(b,c,d,g,h);if(c.proxy)return c;d=ib();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Va||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(jb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");db++;return c}
function ib(){function a(c){return b.call(a.src,a.listener,c)}var b=kb;return a}function R(a,b,c,d,e){if(Array.isArray(b)){for(var h=0;h<b.length;h++)R(a,b[h],c,d,e);return null}c=fb(c);return a&&a[Xa]?a.h(b,c,D(d)?!!d.capture:!!d,e):gb(a,b,c,!0,d,e)}function jb(a){return a in cb?cb[a]:cb[a]="on"+a}
function kb(a,b){if(a.g)a=!0;else{b=new Q(b,this);var c=a.listener,d=a.h||a.src;if(a.D&&"number"!==typeof a&&a&&!a.g){var e=a.src;if(e&&e[Xa])e.i(a);else{var h=a.type,g=a.proxy;e.removeEventListener?e.removeEventListener(h,g,a.capture):e.detachEvent?e.detachEvent(jb(h),g):e.addListener&&e.removeListener&&e.removeListener(g);db--;if(h=hb(e)){g=a.type;var f;if(f=g in h.g){f=h.g[g];var k=Ba(f,a),l;(l=0<=k)&&Array.prototype.splice.call(f,k,1);f=l}f&&($a(a),0==h.g[g].length&&(delete h.g[g],h.h--));0==
h.h&&(h.src=null,e[bb]=null)}else $a(a)}}a=c.call(d,b)}return a}function hb(a){a=a[bb];return a instanceof ab?a:null}var lb="__closure_events_fn_"+(1E9*Math.random()>>>0);function fb(a){if("function"===typeof a)return a;a[lb]||(a[lb]=function(b){return a.handleEvent(b)});return a[lb]};function mb(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};var S=null,nb=new mb;function ob(a){var b,c,d;return y(function(e){if(1==e.g)return null==S&&(S=P()),null==S||null==S.i?e.return(!0):w(e,nb.promise,2);b=e.i;if(!b.has(a))return e.return(!1);if(S.l)return e.return(!0);c=b.get(a);d=S.i;return e.return(d.g!==c.g?d.g>c.g:d.h!==c.h?d.h>c.h:d.i>=c.i)})};var T=new Set(["type","enum","const"]);function U(a,b,c){a=V(a,b,[void 0===c?"root":c]);return 0<a.length?a:null}function W(a,b,c){return"Object:"+a.join(".")+" Validation:"+b+" Constraint:"+c}function pb(a,b){var c=a.length;if(0<c){for(var d=Array(c),e=0;e<c;e++)d[e]=a[e];a=d}else a=[];a[a.length-1]+="["+b+"]";return a}
function qb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!T.has(e)){var h=!1;switch(e){case "multipleOf":h="number"!==typeof b||0===b%a[e];break;case "minimum":h=b>=a[e]||a.exclusiveMinimum&&b>a[e];break;case "maximum":h=b<=a[e]||a.exclusiveMaximum&&b<a[e];break;case "exclusiveMinimum":case "exclusiveMaximum":break;default:throw Error("Unsupported numeric keywords:"+e);}h||d.push(W(c,e,a[e].toString()))}});return d}
function rb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!T.has(e)){switch(e){case "pattern":var h=(new RegExp(a[e])).test(b);break;case "minLength":h=b.length>=a[e];break;case "maxLength":h=b.length<=a[e];break;default:throw Error("Unsupported string keywords:"+e);}h||d.push(W(c,e,a[e].toString()))}});return d}
function sb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!T.has(e)){var h=a[e];switch(e){case "items":if(Array.isArray(h))for(e=0;e<h.length;e++){var g=pb(c,e);g=V(h[e],b[e],g);null!==g&&(d=M(d,g))}else for(e=0;e<b.length;e++)g=pb(c,e),g=V(h,b[e],g),null!==g&&(d=M(d,g));break;case "maxItems":b.length>h&&d.push(W(c,e,h.toString()));break;case "minItems":b.length<h&&d.push(W(c,e,h.toString()));break;case "uniqueItems":if("boolean"!==typeof h)d.push(W(c,e,h.toString()));else if(h){g=new Set;
for(var f=0;f<b.length;f++){var k=JSON.stringify(b[f]);if(g.has(k)){d.push(W(c,e,h.toString()));break}else g.add(k)}}break;default:throw Error("Unsupported array keywords:"+e);}}});return d}
function tb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!T.has(e)){var h=a[e];switch(e){case "required":for(var g=t(h),f=g.next();!f.done;f=g.next())f=f.value,void 0===b[f]&&d.push(W(c,e,f));break;case "properties":Object.keys(b).forEach(function(k){void 0!==h[k]&&(k=V(h[k],b[k],M(c,k)),null!==k&&(d=M(d,k)))});break;case "minProperties":Ia(b)<h&&d.push(W(c,e,h.toString()));break;case "maxProperties":Ia(b)>h&&d.push(W(c,e,h.toString()));break;case "patternProperties":case "additionalProperties":case "dependencies":case "propertyNames":throw Error("Unsupported object keywords:"+
e);default:throw Error("Unknown object keywords:"+e);}}});return d}
function V(a,b,c){var d=[];if(null!=a.type){d=a.type;switch(d){case "string":var e="string"===typeof b;break;case "number":e="number"===typeof b;break;case "boolean":e="boolean"===typeof b;break;case "null":e=null===b;break;case "object":e=D(b)&&!Array.isArray(b);break;case "integer":e="number"===typeof b&&Number.isInteger(b);break;case "array":e=Array.isArray(b);break;case "date":e=D(b)&&"function"==typeof b.getFullYear;break;default:throw Error("Unsupported field type: "+d);}d=e?[]:[W(c,"type",
d)]}if(0==d.length&&null!=a["enum"]){d=a["enum"];e=!1;if(D(b))for(var h=t(d),g=h.next();!g.done;g=h.next()){if(Ja(b,g.value)){e=!0;break}}else for(h=t(d),g=h.next();!g.done;g=h.next())if(b===g.value){e=!0;break}d=e?[]:[W(c,"enum",JSON.stringify(d))]}0==d.length&&null!=a["const"]&&(d=a["const"],d=(D(b)?Ja(d,b):b===d)?[]:[W(c,"const",JSON.stringify(d))]);if(d.length)return d;"number"===typeof b?d=qb(a,b,c):"string"===typeof b?d=rb(a,b,c):Array.isArray(b)?d=sb(a,b,c):D(b)&&!Array.isArray(b)&&(d=tb(a,
b,c));return d};var ub={type:"object",properties:{apiVersion:{type:"number"},apiVersionMinor:{type:"number"},allowedPaymentMethods:{type:"array",items:{type:"object",required:["type"]},minItems:1},transactionInfo:{type:"object",properties:{totalPrice:{type:"string",pattern:"^[0-9]+(\\.[0-9][0-9])?$"},totalPriceStatus:{type:"string"},currencyCode:{type:"string"},transactionNote:{type:"string"}},required:["totalPriceStatus","currencyCode"]}},required:["apiVersion","apiVersionMinor","allowedPaymentMethods","transactionInfo"]},
vb={type:"object",properties:{type:{type:"string"},parameters:{type:"object",required:["payeeVpa","payeeName","mcc","transactionReferenceId"],properties:{payeeName:{type:"string",minLength:1},transactionReferenceId:{type:"string",minLength:1}}},tokenizationSpecification:{type:"object",properties:{type:{type:"string","enum":["DIRECT"]}},required:["type"]}},required:["parameters","tokenizationSpecification","type"]},wb={type:"object",properties:{text:{type:"string",maxLength:150},url:{type:"string",
maxLength:2E3,pattern:"^https://microapps.google.com/"},title:{type:"string",maxLength:80},imageUrl:{type:"string",maxLength:2E3},microappId:{type:"string",maxLength:25}}},xb={type:"object",properties:{allowedMimeTypes:{type:"array",items:{type:"string"},minItems:1},allowedSources:{type:"array",items:{type:"string"}},cameraDirection:{type:"string","enum":["front","back"]},maxVideoSeconds:{type:"number",minimum:1,maximum:5}},required:["allowedMimeTypes"]};function yb(a){var b=U(ub,a,"paymentRequest");if(b)return X(JSON.stringify(b));b=t(a.allowedPaymentMethods);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d;a:{if("UPI"===c.type&&(d=U(vb,c))){d=JSON.stringify(d);break a}d=null}if(d)return X(d);if(c=zb(c,a.transactionInfo))return X(c)}return a.environment&&(a=Ab(a.allowedPaymentMethods,a.environment))?X(a):null}function Bb(a){return null!=a&&D(a)?null:X("Valid order object is required for this API.")}
function Cb(a){if(null==a||!D(a))return X("Valid mediaRequest object is required for this API.");var b=U(xb,a,"mediaRequest");if(b)return X(JSON.stringify(b));b=t(a.allowedMimeTypes);for(var c=b.next();!c.done;c=b.next())if(c=ya.has(c.value)?null:"Request must contain supported media types.")return X(c);if(b=1==a.allowedMimeTypes.length&&"video/*"===a.allowedMimeTypes[0])b=P(),b=!(b.l||(1==b.g||3==b.g)&&54<b.i.g||Db(b)||2===b.g&&115<b.i.g);if(b)return X("Client does not support video requests. Please update the Google Pay app.");
b=P();b=b.l||(1==b.g||3==b.g)&&57<b.i.g||Db(b)||2===b.g&&115<b.i.g;if(1===a.allowedMimeTypes.length&&"application/pdf"===a.allowedMimeTypes[0]&&!b)return X("Client does not support file requests. Please update the Google Pay app.");if(!a.allowedSources)return null;c=t(a.allowedSources);for(var d=c.next();!d.done;d=c.next())if(d=za.has(d.value)?null:"Request must contain supported media sources.")return X(d);return 1!==a.allowedSources.length||"files"!==a.allowedSources[0]||b?1===a.allowedSources.length&&
"camera"===a.allowedSources[0]&&a.allowedMimeTypes.includes("application/pdf")?X('Not possible to request "application/pdf" MIME type with only "camera" in "allowedSources"'):null:X("CLIENT_UNSUPPORTED_FOR_FILES")}
function zb(a,b){if("NOT_CURRENTLY_KNOWN"!==b.totalPriceStatus&&!(0<Number(b.totalPrice)))return"Amount must be greater than 0";if("UPI"===a.type){if("FINAL"!==b.totalPriceStatus)return'Only "FINAL" is supported now in totalPriceStatus for UPI payment type.';if("INR"!==b.currencyCode)return'Only "INR" is currently supported in currencyCode for UPI payment type.'}else if("CARD"===a.type&&!b.transactionId)return"transactionInfo.transactionId is required.";return null}
function Ab(a,b){return a.find(function(c){return"CARD"===c.type})?"TEST"!=b?'only "TEST" environment is supported for CARD payment type.':null:'"environment" is supported for CARD payment type only.'}function Db(a){var b=a.i;return 5==a.g&&(1<b.g||1==b.g&&23<=b.h)}function X(a){return new G(a,3)};function Eb(a){var b=this;this.g=a;this.j=0;this.h=new Map;this.l=new Promise(function(c){return b.s=c});this.g.addEventListener("message",this.i.bind(this));this.g.start()}Eb.prototype.i=function(a){if((a=a.data)&&null!=a.id)if(0===a.type)"acceptConnection"===a.name&&this.s();else if(1===a.type){var b=a.id,c=this.h.get(b);c&&(this.h.delete(b),null!=a.error?c.reject(new G("Request "+a.name+" failed: "+a.error,a.errorCode)):c.resolve(a.data))}};
Eb.prototype.m=function(a,b,c){var d=this;c=void 0===c?!0:c;var e=++this.j,h=Promise.resolve();c&&(h=new Promise(function(f,k){d.h.set(e,{resolve:f,reject:k})}));var g={id:e,type:0,name:a,data:b,isResponseRequired:c};this.l.then(function(){d.g.postMessage(g)});return h};function Fb(a){this.g=a;this.h={}}ta(Fb,Ta);var Gb=[];function Hb(a,b,c){var d="nativeBridge";Array.isArray(d)||(d&&(Gb[0]=d.toString()),d=Gb);for(var e=0;e<d.length;e++){var h=eb(b,d[e],c||a.handleEvent,!1,a.g||a);if(!h)break;a.h[h.key]=h}}Fb.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Ib(a){this.h=a;this.i=new Fb(this);Jb(this);this.g=null}function Kb(a,b){Fa?(a=a.h.paisaJSHost_,null!=a&&a.callNative(JSON.stringify(b))):Ga&&(a=a.h.webkit.messageHandlers.paisaJSHost_,null!=a&&a.postMessage(JSON.stringify(b)))}function Lb(a,b){a.g=b}function Jb(a){Hb(a.i,a.h,function(b){b=b.H;null!=b.detail&&null!=a.g&&a.g(b.detail)})};function Mb(a){var b=this;this.l=Math.floor(65535*Math.random());this.j=this.h=null;this.g=new Map;this.i=new Ib(a);Lb(this.i,function(c){if(!(!c||"object"!==typeof c&&"function"!==typeof c||"string"!==typeof c.status||"success"!==c.status&&"failure"!==c.status||"number"!==typeof c.id)){var d=c.data;if(c.id===b.j)null!=b.h&&"string"===typeof d&&b.h.resolve(d);else{var e=b.g.get(c.id);e&&(b.g.delete(c.id),c.method!==e.request.method?e.S.reject(new G("Method names in request and response are not the same. Request:"+
(e.request.method+" Response:"+c.method))):"success"===c.status?e.S.resolve(d):e.S.reject(new G(d,c.errorCode)))}}});this.h=new mb;this.j=Nb(this);Kb(this.i,{token:"",method:"startConnection",id:this.j,data:{},isResponseRequired:!0});this.s=this.h.promise}
Mb.prototype.m=function(a,b,c){c=void 0===c?!0:c;var d=this,e,h,g,f;return y(function(k){if(1==k.g)return w(k,d.s,2);e=k.i;h=Nb(d);g={token:e,method:a,id:h,data:b,isResponseRequired:c};Kb(d.i,g);if(!c)return k.return(Promise.resolve());f=new mb;d.g.set(h,{S:f,request:g});return k.return(f.promise)})};function Nb(a){var b=a.l;a.l=(b+1)%65535;a.g.has(b);return b};var Ob=null;
function Pb(){var a=window;if(a.self===a.top&&P().h)this.g=new Mb(a);else{var b=Ob=new MessageChannel;try{var c=a.self!==a.top}catch(e){c=!0}if(!c)throw Error("Unsupported environment: expected running in iframe");c=new Eb(b.port1);if(!a.location.ancestorOrigins||!a.location.ancestorOrigins.length)throw Error("unsupported environment");var d=a.location.ancestorOrigins[0];if(!Ha.test(d))throw Error("unknown viewer origin");a.parent.postMessage({type:0,name:"requestConnection"},d,[b.port2]);this.g=
c}}Pb.prototype.m=function(a,b,c){return this.g.m(a,b,void 0===c?!0:c)};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Qb;try{new URL("s://g"),Qb=!0}catch(a){Qb=!1}var Rb=Qb;function Sb(){if(!Rb){a:{var a=document.createElement("a");try{a.href=O}catch(b){a=void 0;break a}a=a.protocol;a=":"===a||""===a?"https:":a}return a}try{a=new URL(O)}catch(b){return"https:"}return a.protocol};var Tb=null;function Ub(){var a=window;this.g=new Pb;this.h=a}function Y(){Tb||(Tb=new Ub);return Tb}n=Ub.prototype;n.C=function(){var a;(a=this.h.self===this.h.top)||(a=this.h,a=Na(a)&&Oa(a));if(a)Vb(this,"sdkload");else{a=this.h.location;var b=O instanceof N?O instanceof N&&O.constructor===N?O.g:"type_error:SafeUrl":"javascript:"!==Sb()?O:void 0;void 0!==b&&(a.href=b)}};function Vb(a,b,c){a.g.m("appLoadingComplete",{loadType:b,loadTimeMs:void 0===c?null:c})}
n.K=function(a){var b=this,c,d,e,h,g;return y(function(f){if(1==f.g)return c=a||{},d="getIdentity",e=c.testVersion,w(f,b.v("nativeGetIdentity"),2);if(3!=f.g)return h=f.i,w(f,b.v("webGetIdentity"),3);g=f.i;e&&"v1"===e.toLowerCase()?d="getIdentity":e&&"v2"===e.toLowerCase()?d="nativeGetIdentity":g?d="getIdentity":h&&(d="nativeGetIdentity");return f.return(b.g.m(d,c))})};n.L=function(){return this.g.m("getPeerInfo",{})};
n.P=function(a){var b=yb(a);return b?Promise.reject(b):this.g.m("requestPayment",a)};n.R=function(a){var b;if(b=(b=U(wb,a,"sharingRequest"))?X(JSON.stringify(b)):null)return Promise.reject(b);Wb(a.imageUrl)||(a.imageUrl="");return this.g.m("requestSharing",a)};n.F=function(a){var b=this,c,d;return y(function(e){if(1==e.g)return(c=Bb(a))?e.return(Promise.reject(c)):w(e,b.g.m("createOrder",a),2);d=e.i;"object"===typeof d&&(d.toString=function(){return JSON.stringify(d)});return e.return(d)})};
n.G=function(a){var b=this,c;return y(function(d){return(c=Bb(a))?d.return(Promise.reject(c)):d.return(b.g.m("createPeerOrder",a))})};n.J=function(a){return this.g.m("getCurrentLocation",a||{})};n.M=function(a){return this.g.m("getPhoneNumber",a||{})};n.N=function(a){this.g.m("openUrl",a).catch(function(){})};n.O=function(a){var b=Cb(a);return b?Promise.reject(b):this.g.m("requestMedia",a)};n.I=function(a){return this.g.m("getAddress",a||{})};n.v=function(a){return ob(a)};
function Wb(a){if(!a||"https"!==(a.match(La)[1]||"").toLowerCase())return!1;var b=Ma(a.match(La)[3]||null)||"";return[".google.com",".googleapis.com",".gstatic.com",".googleusercontent.com"].some(function(c){return 0==Aa(c,b.slice(b.length-c.length))})}
(function(a){var b,c;return y(function(d){b=window;if(!(Na(b)&&Oa(b)||b.self===b.top&&P().h))return d.return();c=new Map;a().then(function(e){e=e.allowedFeatureConfigs;Array.isArray(e)&&(e.forEach(function(h){return c.set(h.feature,Ra(h.minVersion||""))}),nb.resolve(c))});d.g=0})})(function(){return Y().g.m("getAllowedFeatureConfigs",{})});
(function(a){var b=window;if(b.self===b.top&&P().h)if(b.PerformanceObserver&&(b.PerformanceObserver.supportedEntryTypes||[]).includes("navigation"))try{(new b.PerformanceObserver(function(c){c=t(c.getEntries());for(var d=c.next();!d.done;d=c.next())d=d.value,"navigate"===d.type&&0<d.duration&&a(d.duration)})).observe({type:"navigation",buffered:!0})}catch(c){R(b,"load",function(){return a(null)})}else R(b,"load",function(){return a(null)})})(function(a){return Vb(Y(),"onload",a)});
(function(a){try{var b=window;(Na(b)&&Oa(b)||b.self===b.top&&P().h)&&R(b,"load",function(){if(b.performance&&b.performance.getEntriesByType&&0!=b.performance.getEntriesByType("paint").length){var c=b.performance.getEntriesByType("paint");c=t(c);for(var d=c.next();!d.done;d=c.next())switch(d=d.value,d.name){case "first-contentful-paint":a(d.startTime+d.duration)}}})}catch(c){}})(function(a){return void Vb(Y(),"fcp",a)});var Z;J=function(){return Y()};Z=new va;var Xb;wa=function(){return Y()};Xb=new xa;F("microapps.getIdentity",Z.K);F("microapps.requestPayment",Z.P);F("microapps.createOrder",Z.F);F("microapps.createPeerOrder",Xb.G);F("microapps.initialize",Z.C);F("microapps.getCurrentLocation",Z.J);F("microapps.getPhoneNumber",Z.M);F("microapps.getPeerInfo",Xb.L);F("microapps.openUrl",Z.N);F("microapps.requestSharing",Z.R);F("microapps.requestMedia",Z.O);F("microapps.getAddress",Z.I);
F("microapps.checkFeatureAvailability",Z.v);F("microapps.environment",function(){return Pa.test(K().toLocaleLowerCase())?"gpay-microapps":""});}).call(this);
